"""empty message

Revision ID: 71796a168a25
Revises: 80fa5abc88f2
Create Date: 2025-07-29 18:05:00.534064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71796a168a25'
down_revision = '80fa5abc88f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
